# Generated by Django 4.2.2 on 2023-06-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
                ('place', models.CharField(max_length=20, null=True)),
                ('habitat_temperature', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('image', models.FileField(max_length=500, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('habitat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petApp.habitat')),
            ],
        ),
    ]
